import type { Metadata } from "next";
import "../styles/globals.css";
import {Open_Sans} from "next/font/google"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open_sans",  
});

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${open_sans.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
